package compton_data

import "github.com/arelate/southern_light/vangogh_integration"

var CompatibilityProperties = []string{
	vangogh_integration.SteamDeckAppCompatibilityCategoryProperty,
	vangogh_integration.SteamMachineCompatibilityCategoryProperty,
	vangogh_integration.SteamFrameCompatibilityCategoryProperty,
	vangogh_integration.SteamSteamOsAppCompatibilityCategoryProperty,
	vangogh_integration.ProtonDbTierProperty,
	vangogh_integration.ProtonDbConfidenceProperty,
}
