package compton_data

import (
	"github.com/arelate/vangogh_local_data"
)

var PropertyTitles = map[string]string{
	vangogh_local_data.TitleProperty:                             "Title",
	vangogh_local_data.DescriptionOverviewProperty:               "Description",
	vangogh_local_data.TagIdProperty:                             "Account Tags",
	vangogh_local_data.LocalTagsProperty:                         "Local Tags",
	vangogh_local_data.SteamTagsProperty:                         "Steam Tags",
	vangogh_local_data.OperatingSystemsProperty:                  "OS",
	vangogh_local_data.DevelopersProperty:                        "Developers",
	vangogh_local_data.PublishersProperty:                        "Publishers",
	vangogh_local_data.EnginesProperty:                           "Engine",
	vangogh_local_data.EnginesBuildsProperty:                     "Engine Build",
	vangogh_local_data.SeriesProperty:                            "Series",
	vangogh_local_data.GenresProperty:                            "Genres",
	vangogh_local_data.StoreTagsProperty:                         "Store Tags",
	vangogh_local_data.FeaturesProperty:                          "Features",
	vangogh_local_data.LanguageCodeProperty:                      "Language",
	vangogh_local_data.IncludesGamesProperty:                     "Includes",
	vangogh_local_data.IsIncludedByGamesProperty:                 "Included By",
	vangogh_local_data.RequiresGamesProperty:                     "Requires",
	vangogh_local_data.IsRequiredByGamesProperty:                 "Required By",
	vangogh_local_data.ProductTypeProperty:                       "Product Type",
	vangogh_local_data.WishlistedProperty:                        "Wishlisted",
	vangogh_local_data.OwnedProperty:                             "Owned",
	vangogh_local_data.IsFreeProperty:                            "Free",
	vangogh_local_data.IsDiscountedProperty:                      "On Sale",
	vangogh_local_data.PreOrderProperty:                          "Pre-order",
	vangogh_local_data.ComingSoonProperty:                        "Coming Soon",
	vangogh_local_data.InDevelopmentProperty:                     "In Development",
	vangogh_local_data.TypesProperty:                             "Data Type",
	vangogh_local_data.SteamReviewScoreDescProperty:              "Steam Reviews",
	vangogh_local_data.SteamDeckAppCompatibilityCategoryProperty: "Steam Deck",
	vangogh_local_data.ProtonDBTierProperty:                      "ProtonDB Tier",
	vangogh_local_data.ProtonDBConfidenceProperty:                "ProtonDB Confidence",
	vangogh_local_data.SortProperty:                              "Sort",
	vangogh_local_data.DescendingProperty:                        "Descending",
	vangogh_local_data.GlobalReleaseDateProperty:                 "Global Release",
	vangogh_local_data.GOGReleaseDateProperty:                    "GOG.com Release",
	vangogh_local_data.GOGOrderDateProperty:                      "GOG.com Order",
	vangogh_local_data.ProductValidationResultProperty:           "Validation Result",
	vangogh_local_data.RatingProperty:                            "Rating",
	vangogh_local_data.PriceProperty:                             "Price",
	vangogh_local_data.BasePriceProperty:                         "Base Price",
	vangogh_local_data.DiscountPercentageProperty:                "Discount",

	vangogh_local_data.HLTBHoursToCompleteMainProperty: "HLTB Main Story",
	vangogh_local_data.HLTBHoursToCompletePlusProperty: "HLTB Story + Extras",
	vangogh_local_data.HLTBHoursToComplete100Property:  "HLTB Completionist",
	vangogh_local_data.HLTBGenresProperty:              "HLTB Genres",
	vangogh_local_data.HLTBPlatformsProperty:           "HLTB Platforms",
	vangogh_local_data.HLTBReviewScoreProperty:         "HLTB Review Score",

	GauginGOGLinksProperty:   "GOG.com Links",
	GauginOtherLinksProperty: "Other Links",
	GauginSteamLinksProperty: "Steam Links",

	vangogh_local_data.ForumUrlProperty:   "Forum",
	vangogh_local_data.StoreUrlProperty:   "Store",
	vangogh_local_data.SupportUrlProperty: "Support",

	GauginSteamCommunityUrlProperty: "Community",

	GauginGOGDBUrlProperty:        "GOGDB",
	GauginIGDBUrlProperty:         "IGDB",
	GauginHLTBUrlProperty:         "HLTB",
	GauginMobyGamesUrlProperty:    "MobyGames",
	GauginPCGamingWikiUrlProperty: "PCGamingWiki",
	GauginProtonDBUrlProperty:     "ProtonDB",
	GauginStrategyWikiUrlProperty: "StrategyWiki",
	GauginWikipediaUrlProperty:    "Wikipedia",
	GauginWineHQUrlProperty:       "WineHQ",
	GauginVNDBUrlProperty:         "VNDB",
	GauginIGNWikiUrlProperty:      "IGN Wiki",
}
